using Rokkan.Prophecy.Sim;
using UnityEngine;
using UnityEngine.InputSystem;

namespace Rokkan.Prophecy.Presentation
{
    /// <summary>
    /// Reads the Input System and turns it into <see cref="InputFrame"/>s for the sim. The only
    /// channel by which a device may influence gameplay.
    ///
    /// <para>It makes no decisions. It does not know what jumping is, whether the character is
    /// grounded, or whether an action is currently permitted — it reports which buttons a human
    /// touched, and the sim decides what that means. That restraint is the whole reason the sim
    /// can run with no devices attached.</para>
    ///
    /// <para><b>Execution order is load-bearing.</b> This samples at -100, ahead of
    /// <c>SimClockDriver</c> at 0, so every frame is sampled before the clock retires the ticks
    /// that will consume it. Get that backwards and input is always one frame stale.</para>
    ///
    /// <para>Focus loss clears the latches: a button released while the window was in the
    /// background would otherwise stay held forever, and the character would run into a wall
    /// until the player pressed and released it again.</para>
    /// </summary>
    [DefaultExecutionOrder(-100)]
    public sealed class PlayerInputCapture : MonoBehaviour, IInputSource
    {
        [Header("Actions")]
        [SerializeField, Tooltip("Prophecy.inputactions. Generated by Prophecy > Build > Generate Input Actions.")]
        private InputActionAsset _actions;

        [SerializeField]
        private string _gameplayMapName = "Gameplay";

        private InputActionMap _map;

        private InputAction _move;
        private InputAction _jump;
        private InputAction _attack;
        private InputAction _block;
        private InputAction _parry;
        private InputAction _dodge;
        private InputAction _flameArt;
        private InputAction _interact;
        private InputAction _runToggle;

        private Vector2 _moveValue;
        private ButtonLatch _jumpLatch;
        private ButtonLatch _attackLatch;
        private ButtonLatch _blockLatch;
        private ButtonLatch _parryLatch;
        private ButtonLatch _dodgeLatch;
        private ButtonLatch _flameArtLatch;
        private ButtonLatch _interactLatch;
        private ButtonLatch _runToggleLatch;

        private bool _resolved;

        /// <summary>True once the action map resolved. False means every frame reports neutral.</summary>
        public bool IsReady => _resolved;

        private void Awake() => Resolve();

        private void OnEnable()
        {
            if (_resolved) _map.Enable();
        }

        private void OnDisable()
        {
            if (_resolved) _map.Disable();
            ClearLatches();
        }

        private void Update()
        {
            if (!_resolved) return;

            _moveValue = _move.ReadValue<Vector2>();

            _jumpLatch.Sample(_jump.IsPressed());
            _attackLatch.Sample(_attack.IsPressed());
            _blockLatch.Sample(_block.IsPressed());
            _parryLatch.Sample(_parry.IsPressed());
            _dodgeLatch.Sample(_dodge.IsPressed());
            _flameArtLatch.Sample(_flameArt.IsPressed());
            _interactLatch.Sample(_interact.IsPressed());
            _runToggleLatch.Sample(_runToggle.IsPressed());
        }

        private void OnApplicationFocus(bool hasFocus)
        {
            if (!hasFocus) ClearLatches();
        }

        /// <summary>
        /// Build the frame for one sim tick and clear the consumed edges. Called from inside the
        /// tick, not from Update — if two ticks retire in one frame, the second must see the held
        /// buttons but not a second copy of the same press.
        /// </summary>
        public InputFrame ConsumeFrame()
        {
            if (!_resolved) return InputFrame.Empty;

            return new InputFrame(
                _moveValue,
                jump: _jumpLatch.Consume(),
                attack: _attackLatch.Consume(),
                block: _blockLatch.Consume(),
                parry: _parryLatch.Consume(),
                dodge: _dodgeLatch.Consume(),
                flameArt: _flameArtLatch.Consume(),
                interact: _interactLatch.Consume(),
                runToggle: _runToggleLatch.Consume());
        }

        private void ClearLatches()
        {
            _moveValue = Vector2.zero;
            _jumpLatch.Clear();
            _attackLatch.Clear();
            _blockLatch.Clear();
            _parryLatch.Clear();
            _dodgeLatch.Clear();
            _flameArtLatch.Clear();
            _interactLatch.Clear();
            _runToggleLatch.Clear();
        }

        private void Resolve()
        {
            if (_actions == null)
            {
                Debug.LogError($"{name}: no InputActionAsset assigned. Generate one with " +
                               "Prophecy > Build > Generate Input Actions and assign it here.", this);
                return;
            }

            _map = _actions.FindActionMap(_gameplayMapName, throwIfNotFound: false);
            if (_map == null)
            {
                Debug.LogError($"{name}: '{_gameplayMapName}' action map not found in {_actions.name}.", this);
                return;
            }

            _move = Find("Move");
            _jump = Find("Jump");
            _attack = Find("Attack");
            _block = Find("Block");
            _parry = Find("Parry");
            _dodge = Find("Dodge");
            _flameArt = Find("FlameArt");
            _interact = Find("Interact");
            _runToggle = Find("RunToggle");

            _resolved = _move != null && _jump != null && _attack != null && _block != null &&
                        _parry != null && _dodge != null && _flameArt != null && _interact != null &&
                        _runToggle != null;

            if (_resolved && isActiveAndEnabled) _map.Enable();
        }

        private InputAction Find(string actionName)
        {
            var action = _map.FindAction(actionName, throwIfNotFound: false);
            if (action == null)
                Debug.LogError($"{name}: action '{actionName}' missing from the " +
                               $"'{_gameplayMapName}' map. Regenerate the input asset.", this);
            return action;
        }
    }
}
